# Generated by Django 4.1 on 2023-01-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=1000)),
                ("updated", models.CharField(max_length=20)),
                ("plus", models.CharField(max_length=1000)),
            ],
        ),
    ]
