# Generated by Django 4.1.5 on 2023-01-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="href",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
