# Generated by Django 4.1 on 2023-01-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_article_href"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="content_noun",
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="detail",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="title_noun",
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
