# Generated by Django 4.1.5 on 2023-02-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_inversetable_rename_updated_article_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content_noun",
            field=models.TextField(null=True),
        ),
    ]
