# Generated by Django 4.1 on 2023-01-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_article_content_noun_article_detail_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="plus",
        ),
        migrations.AddField(
            model_name="article",
            name="file",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
