# Generated by Django 4.1.5 on 2023-02-03 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_remove_article_content_noun"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContentInverseTable",
        ),
        migrations.DeleteModel(
            name="InverseTable",
        ),
    ]
