# Generated by Django 4.1.5 on 2023-02-03 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_contentinversetable_inversetable"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContentInverseTable",
        ),
        migrations.DeleteModel(
            name="InverseTable",
        ),
    ]
