# Generated by Django 4.1.6 on 2023-02-09 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_inversetable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="전체교육",
        ),
        migrations.RemoveField(
            model_name="article",
            name="행사",
        ),
    ]
